# Use Node.js image to build the apps
FROM node:23.5 AS build

WORKDIR /app

# Copy the entire repo into the container
COPY . .

#COPY 404.html /usr/share/nginx/html/404.html

# Install dependencies
RUN yarn install

# Build each app
RUN yarn workspace demo build


# Serve each app using NGINX
FROM nginx:alpine

# Copy built files for each app into their respective directories
COPY --from=build /app/apps/demo/dist /usr/share/nginx/html/demo

# Use a custom NGINX configuration (replace main nginx.conf)
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port NGINX will use
EXPOSE 3000

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]


