# Use Node.js image to build the apps
FROM node:23.5 AS build

# Set the working directory
WORKDIR /app

# Copy the entire repo into the container
COPY . .

# Set build arguments (you can add more arguments if needed)
ARG VITE_HUGGING_FACE_TOKEN

# Create .env file with the build arguments
RUN echo "VITE_HUGGING_FACE_TOKEN=${VITE_HUGGING_FACE_TOKEN}" > .env

# Install dependencies
RUN yarn install

# Build each app
RUN yarn workspace demo build

# Serve each app using NGINX
FROM nginx:alpine

# Copy built files for each app into their respective directories
COPY --from=build /app/apps/demo/dist /usr/share/nginx/html/demo

# Use a custom NGINX configuration (replace main nginx.conf)
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port NGINX will use
EXPOSE 3000

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
