version: '3'

services:
  website:
    build:
        context: .
        dockerfile: Dockerfile-website
    ports:
      - "80:80"
  demo:
    build:
        context: .
        dockerfile: Dockerfile-demo
    ports:
      - "3000:3000"