name: Aralects Monorepo CI/CD

on:
  push:
    branches:
      - staging  # Trigger on push to the staging branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Landing Page (Port 88 STAGING)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aralects-staging-landing:${{ github.sha }} -f Dockerfile-website .
          docker push ${{ secrets.DOCKER_USERNAME }}/aralects-staging-landing:${{ github.sha }}

      - name: Build and Push Demo (Port 3008 STAGING)
        run: |
          docker build \
            --build-arg VITE_HUGGING_FACE_TOKEN=${{ secrets.VITE_HUGGING_FACE_TOKEN }} \
            -t ${{ secrets.DOCKER_USERNAME }}/aralects-staging-demo:${{ github.sha }} \
            -f Dockerfile-demo .
          docker push ${{ secrets.DOCKER_USERNAME }}/aralects-staging-demo:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Authenticate Docker on EC2
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Deploy Landing Page (Port 88)
            docker pull ${{ secrets.DOCKER_USERNAME }}/aralects-staging-landing:${{ github.sha }}
            # Stop and remove the container only if it exists
            docker ps -a --filter "name=aralects-staging-landing" -q | grep -q . && docker stop aralects-staging-landing && docker rm aralects-staging-landing
            docker run -d -p 88:80 --env-file /app/mono-repo/.env --name aralects-staging-landing ${{ secrets.DOCKER_USERNAME }}/aralects-staging-landing:${{ github.sha }}

            # Deploy Demo (Port 3008)
            docker pull ${{ secrets.DOCKER_USERNAME }}/aralects-staging-demo:${{ github.sha }}
            # Stop and remove the container only if it exists
            docker ps -a --filter "name=aralects-staging-demo" -q | grep -q . && docker stop aralects-staging-demo && docker rm aralects-staging-demo
            docker run -d -p 3008:3000 --env-file /app/mono-repo/.env --name aralects-staging-demo ${{ secrets.DOCKER_USERNAME }}/aralects-staging-demo:${{ github.sha }}

            # Verify that both containers are running
            if ! docker ps -q --filter name=aralects-staging-landing | grep -q .; then
              echo "Landing page container failed!"
              exit 1
            fi
            if ! docker ps -q --filter name=aralects-staging-demo | grep -q .; then
              echo "Demo container failed!"
              exit 1
            fi
